### ISSUE TITLE
May we freely create documents herein, or better awaiting the availability of a clear repository structure?

### ISSUE THREAD

**Issue by Glottocrisio** [bpmlod/Neuro-symbolic_LLOD_report#4]
I just wanted to break the ice creating a document listing useful papers on Neurosymbolic for our domain, but I want to abide to some convention (including title nomenclature, or even font/spacing, etc.).

**Comment by Glottocrisio** [comment]
For clarification, I can see that Andon opened issues already aggregate the material we need, according to the specific questions we have agreed upon. However, I foresee at a certain point text documents containing collected information in a structured way shall be created, leaving the github issues for eventual discussion upon updates/deletions in the main docs.  For the moment I will just contribute to the issues.

**Comment by twktheainur** [comment]
Please feel free to create any relevant issues. Just make sure you add material corresponding to existing issues in those issues so that we don't scatter the information too much, but yes new issues can cover any additional aspects that you believe to be relevant.
